### PR TITLE
base: Allow repairing bases with credits from the bank (12.10.20)

### PR DESCRIPTION
**Pull request by dd84ai**
replacement to this branch https://github.com/DiscoveryGC/FLHook/pull/109
I had difficulties restoring old one
+I remade heavily anyway;

What I fixed: 
1) any repair mod can be turned on/off now by base owner.
2) it works precisely only when base is having 100% health now, and just blocks tear/wear damage with substracting necessary money instead of real repairs.

btw description of idea behind it just in case:
when base is damaged or in siege, it is repaired with repair materials as usual
when it has 100% health, it is repaired with money (I made it as a thing that can turned on/off by base owner)
FOW is just removed.

### CODE REVIEW

**Review by dsyalex — COMMENTED** [review]
please squash

**Comment by dd84ai** [comment]
squashed

**Comment by dsyalex** [comment]
When we have squashed commits, please can we have useful commit messages that contain the full context and thinking for the commit?

**Review by dsyalex — CHANGES_REQUESTED** [review]
(setting review state)

**Comment by dd84ai** [comment]
All righty. Goot commit descriptions for every pull request!

**Comment by dd84ai** [comment]
Reading through PR again, and thinking if I was drunk when I was writing it

**Pull request closed without merging**
