### PR TITLE
Allow Mining Field Drain to be disabled.

### PR DESCRIPTION
**Pull request by Corran-Raisu**
Add to config under [MiningGeneral] section

; Does mining drain field capacity? 1 is yes, 0 is no.
EnableFieldDrain = 0

### CODE REVIEW

**Review by dsyalex — COMMENTED** [review]
am I going mad or does that not really get used anywhere important beyond the commented out line 597?

**Review by dsyalex — CHANGES_REQUESTED** [review]
please respond to comments

**Comment by dd84ai** [comment]
> please respond to comments

https://discord.com/channels/444137064439742474/456086070862413824/754801027844145202

**Comment by dsyalex** [comment]
This is now hopelessly outdated

**Pull request closed without merging**
