### PR TITLE
base: Priority to active recipe over repair (Requires fixing)

### PR DESCRIPTION
**Pull request by dd84ai**
When player builds something, it often requires some precise numbers like... 10'000 Robotic hardware being consumed.
During its crafting he brings exactly 10'000, but recipe consumes only 9'800
because something like 128 units of robotic hardware become consumed for base repair.

This fix prevents it. If the repair materials is still needed in active crafting recipe, it will be not consumed for repairs. Only for crafting. 

Crafting can be still not finished, but if for example need in robotic hardware need is already zero, it will continue being used for repairs.

### CODE REVIEW

**Review by dsyalex — COMMENTED** [review]
This sounds dangerous - while a recipe requiring some repair-commodity is in the process of being made, you can't repair the base?

**Comment by dd84ai** [comment]
It is already dangerous so, because recipe consume commodities 100 times faster than repairs done.
This danger is resolved though in... allowing pause/resume to recipes: https://github.com/DiscoveryGC/FLHook/pull/133

**Comment by dd84ai** [comment]
Anyway, once recipe consumed repair materials, base continues to repair even if recipe is not finished yet.

**Comment by dsyalex** [comment]
So, in other words, repair takes priority at the moment, but at such a slow rate that if an active recipe needs that cargo, the majority of it will go to the recipe before the next repair attempt, not providing a great deal of repair value but annoying the players trying to give it resources for the recipe?

**Comment by dd84ai** [comment]
> So, in other words, repair takes priority at the moment, but at such a slow rate that if an active recipe needs that cargo, the majority of it will go to the recipe before the next repair attempt, not providing a great deal of repair value but annoying the players trying to give it resources for the recipe?

Exactly.

**Comment by dd84ai** [comment]
I realized the lack of compatibility with the pause/resume features.

**Pull request closed without merging**
