### PR TITLE
Hyper scanner fix

### PR DESCRIPTION
**Pull request by dd84ai**
You can /survey while being bumped by NPC within 400 distance by x, y, z (not 5 as before)

### CODE REVIEW

**Comment by dd84ai** [comment]
This fix would allow to be not disrupting hyper space survey when you are bumped by different NPCs around during hyper

**Review by dsyalex — CHANGES_REQUESTED** [review]
Per Discord, this code looks like it will allow charging up to 400m/s (i.e., it's fine to charge while cruising :D), as it's actually checking speed of the ship. What you want is distance from the charge start location :)

**Comment by dd84ai** [comment]
changed

**Review by dsyalex — CHANGES_REQUESTED** [review]
while curr_charge <= charge_rate you'll get pos_start == pos_curr, but as soon as curr_charge > charge_rate you'll get pos_start = {0, 0, 0} at which point you won't be able to charge jump drive except inside the sun

**Comment by dd84ai** [comment]
fixed start_pos

**Review by dsyalex — CHANGES_REQUESTED** [review]
HkDistance3D please

**Review by dsyalex — APPROVED** [review]

**Pull request merged**
